import { Geist, Cormorant_Garamond, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200","300","400","500","600","700","800","900"]
})

// const CormorantGaramond = Cormorant_Garamond({
//     subsets: ["latin"],
//     weight: ["100", "200","300","400","500","600","700","800","900"]
// })
export const metadata = {
  title: "AT Beauty | Unlock Your Natural Glow",
  description: "Generated by create next app",
};
 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.className} antialiased`}
      >
      <AuthProvider>
          <Navbar/>
        {children}
        <Footer/>
      </AuthProvider>
      
      
       
      </body>
    </html>
  );
}
